name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract current branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Gen target branch name
        run: echo "GITHUB_SHA_SHORT= $( if [[ ${{ steps.extract_branch.outputs.branch }} == release* ]]; then echo release; elif [[ ${{ steps.extract_branch.outputs.branch }} == hotfix* ]]; then echo hotfix ;else echo ${{ steps.extract_branch.outputs.branch }} ; fi)" >> $GITHUB_ENV
        id: get_target_branch

      - name: Test
        run: echo ${GITHUB_SHA_SHORT}
