name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    env:
      branch_to_push: main1
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo ${GITHUB_REF#refs/heads/} and $branch_to_push
        id: extract_branch
        
      - name: Extract branch name 2
        # run: if [[ ${{ env.branch_to_push }} == main ]]; then echo long; else echo nguyen; fi
        run: echo "GITHUB_SHA_SHORT= $(if [[ ${{ env.branch_to_push }} == main ]]; then echo first; elif [[ ${{ env.branch_to_push }} == main2 ]]; then  echo second;  else  echo last fi)" >> $GITHUB_ENV
        id: extract_branch_2

      - name: Test
        run: echo ${GITHUB_SHA_SHORT}
