name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "AAABBB=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "AAABBB= $(if [[ ${{ AAABBB }} == main ]]; then echo long; elif [[ ${{ AAABBB }} == main2 ]]; then "viet"; else echo nguyen; fi)" >> $GITHUB_ENV
      
      - name: Test
        run: echo ${AAABBB}

