name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Extract branch name 2
        run: echo "GITHUB_SHA_SHORT= $(if [[ ${{ steps.extract_branch.outputs.branch }} == main ]]; then echo long; elif [[ ${{ steps.extract_branch.outputs.branch }} == main2 ]]; then "viet"; else echo nguyen; fi)" >> $GITHUB_ENV
        id: extract_branch_2

      - name: Test
        run: echo ${GITHUB_SHA_SHORT}
