Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@LongNguyen97 
LongNguyen97
/
test_cicd
Public
Code
Issues
Pull requests
2
Actions
Projects
Wiki
Security
Insights
Settings
test_cicd/.github/workflows/post-merged-code-actions.yaml
@LongNguyen97
LongNguyen97 Update post-merged-code-actions.yaml
Latest commit bb91ca9 3 minutes ago
 History
 1 contributor
21 lines (17 sloc)  522 Bytes
   
name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    env:
      branch_to_push: main1
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo ${GITHUB_REF#refs/heads/} and $branch_to_push
        id: extract_branch
        
      - name: Extract branch name 2
        # run: if [[ ${{ env.branch_to_push }} == main ]]; then echo long; else echo nguyen; fi
        run: echo "if [[ ${{ env.branch_to_push }} == main ]]; then echo long; else echo nguyen; fi" >> $GITHUB_ENV
        id: extract_branch_2

      - name: Test
          run: echo $GITHUB_SHA_SHORT
