name: getBranchName
on: [push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo ${GITHUB_REF#refs/heads/}
        id: extract_branch
